/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as FetchMoviesRouteImport } from './routes/fetch-movies'
import { Route as AddEmployeeRouteImport } from './routes/add-employee'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchMoviesRoute = FetchMoviesRouteImport.update({
  id: '/fetch-movies',
  path: '/fetch-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEmployeeRoute = AddEmployeeRouteImport.update({
  id: '/add-employee',
  path: '/add-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-employee': typeof AddEmployeeRoute
  '/fetch-movies': typeof FetchMoviesRoute
  '/table': typeof TableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-employee': typeof AddEmployeeRoute
  '/fetch-movies': typeof FetchMoviesRoute
  '/table': typeof TableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-employee': typeof AddEmployeeRoute
  '/fetch-movies': typeof FetchMoviesRoute
  '/table': typeof TableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/add-employee' | '/fetch-movies' | '/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/add-employee' | '/fetch-movies' | '/table'
  id: '__root__' | '/' | '/about' | '/add-employee' | '/fetch-movies' | '/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddEmployeeRoute: typeof AddEmployeeRoute
  FetchMoviesRoute: typeof FetchMoviesRoute
  TableRoute: typeof TableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetch-movies': {
      id: '/fetch-movies'
      path: '/fetch-movies'
      fullPath: '/fetch-movies'
      preLoaderRoute: typeof FetchMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-employee': {
      id: '/add-employee'
      path: '/add-employee'
      fullPath: '/add-employee'
      preLoaderRoute: typeof AddEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddEmployeeRoute: AddEmployeeRoute,
  FetchMoviesRoute: FetchMoviesRoute,
  TableRoute: TableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
